//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataSDataWebApiDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public System.Guid Invoice_Id { get; set; }
        public System.Guid Payment_Id { get; set; }
        public decimal AppliedAmount { get; set; }
        public System.Guid ID { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string ExternalReference { get; set; }
        public string External_Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string SyncHashKey { get; set; }
        public short SyncEndpoint_Id { get; set; }
        public int SyncEndpointTick { get; set; }
        public short EntityStatus { get; set; }
    }
}
