//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataSDataWebApiDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string InvoiceNumber { get; set; }
        public string PONumber { get; set; }
        public string Comments { get; set; }
        public decimal Taxes { get; set; }
        public decimal Total { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.Guid Customer_Id { get; set; }
        public Nullable<System.Guid> BillToContactId { get; set; }
        public Nullable<System.Guid> ShipToContactId { get; set; }
        public Nullable<System.DateTime> InvoiceDueDate { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Salesperson { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipVia { get; set; }
        public string Terms { get; set; }
        public string FOB { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Discount { get; set; }
        public decimal Freight { get; set; }
        public decimal Miscellaneous { get; set; }
        public decimal Payment { get; set; }
        public decimal PaymentDiscount { get; set; }
        public decimal Balance { get; set; }
        public string ExternalReference { get; set; }
        public string External_Id { get; set; }
        public string BillToFirstName { get; set; }
        public string BillToLastName { get; set; }
        public string BillToStreet1 { get; set; }
        public string BillToStreet2 { get; set; }
        public string BillToStreet3 { get; set; }
        public string BillToStreet4 { get; set; }
        public string BillToCity { get; set; }
        public string BillToStateProvince { get; set; }
        public string BillToPostalCode { get; set; }
        public string BillToCountry { get; set; }
        public string BillToPhone { get; set; }
        public string ShipToFirstName { get; set; }
        public string ShipToLastName { get; set; }
        public string ShipToStreet1 { get; set; }
        public string ShipToStreet2 { get; set; }
        public string ShipToStreet3 { get; set; }
        public string ShipToStreet4 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToStateProvince { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToPhone { get; set; }
        public string BillToEmail { get; set; }
        public string ShipToEmail { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string SyncHashKey { get; set; }
        public short SyncEndpoint_Id { get; set; }
        public int SyncEndpointTick { get; set; }
        public short EntityStatus { get; set; }
        public Nullable<System.DateTime> DiscountDueDate { get; set; }
    }
}
