//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataSDataWebApiDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public string Note { get; set; }
        public bool Taxable { get; set; }
        public System.Guid WorkOrder_Id { get; set; }
        public System.Guid ServiceType_Id { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal Discount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
