//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataSDataWebApiDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int Status { get; set; }
        public int PaymentMethod { get; set; }
        public string Recipient { get; set; }
        public string Note { get; set; }
        public string QuickCode { get; set; }
        public System.Guid User_Id { get; set; }
        public System.Guid Customer_Id { get; set; }
        public int Priority { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public Nullable<System.Guid> AssignedTo_Id { get; set; }
        public bool IsEstimate { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Address_Id { get; set; }
        public decimal SubTotal { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string PONumber { get; set; }
        public Nullable<decimal> MaxInvoiceAmount { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string LocationEmail { get; set; }
        public string LocationStreet1 { get; set; }
        public string LocationStreet2 { get; set; }
        public string LocationStreet3 { get; set; }
        public string LocationStreet4 { get; set; }
        public string LocationCity { get; set; }
        public string LocationStateProvince { get; set; }
        public string LocationPostalCode { get; set; }
        public string LocationCountry { get; set; }
        public string LocationPhone { get; set; }
        public string BillingEmail { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public decimal AmountPaid { get; set; }
        public string PaymentReference { get; set; }
        public string AuthorizationCode { get; set; }
        public string CreditCardLast4 { get; set; }
        public string ExpirationMonth { get; set; }
        public string ExpirationYear { get; set; }
        public decimal Tax { get; set; }
        public string DocumentReference { get; set; }
        public decimal Total { get; set; }
        public string TaxTransactionId { get; set; }
        public short ErrorType { get; set; }
    }
}
