//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.Contacts = new HashSet<Contact>();
            this.Addresses = new HashSet<Address>();
            this.Quotes = new HashSet<Quote>();
            this.CustomerPrimaries = new HashSet<CustomerPrimary>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string Name { get; set; }
        public int PaymentMethod { get; set; }
        public string External_Id { get; set; }
        public string ExternalReference { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string SyncHashKey { get; set; }
        public short SyncEndpoint_Id { get; set; }
        public int SyncEndpointTick { get; set; }
        public short EntityStatus { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<CustomerPrimary> CustomerPrimaries { get; set; }
    }
}
