//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string FromAddress { get; set; }
        public string FromDisplayName { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public int Type { get; set; }
        public string Subject { get; set; }
        public string Template { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
