//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public InventoryItem()
        {
            this.InventoryCategories = new HashSet<InventoryCategory>();
            this.InventoryItems1 = new HashSet<InventoryItem>();
            this.InventoryItems = new HashSet<InventoryItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string Sku { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal PriceStd { get; set; }
        public decimal CostStd { get; set; }
        public decimal Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string External_Id { get; set; }
        public string ExternalReference { get; set; }
        public string TaxClass { get; set; }
        public string SyncHashKey { get; set; }
        public short SyncEndpoint_Id { get; set; }
        public int SyncEndpointTick { get; set; }
        public short EntityStatus { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<InventoryCategory> InventoryCategories { get; set; }
        public virtual ICollection<InventoryItem> InventoryItems1 { get; set; }
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
    }
}
