//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemBlob
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public System.Guid InventoryItem_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MimeType { get; set; }
        public string URL { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<System.Guid> AzureContainerKey { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    }
}
