//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid Customer_Id { get; set; }
        public string DocumentNumber { get; set; }
        public int DocumentType { get; set; }
        public string FromDisplayName { get; set; }
        public int Status { get; set; }
        public int EmailType { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
