//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.Blobs = new HashSet<Blob>();
            this.CustomerPortalSettings = new HashSet<CustomerPortalSetting>();
            this.Customers = new HashSet<Customer>();
            this.DocumentTemplates = new HashSet<DocumentTemplate>();
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.IntegrationErrors = new HashSet<IntegrationError>();
            this.InventoryCategories = new HashSet<InventoryCategory>();
            this.InventoryItems = new HashSet<InventoryItem>();
            this.ServiceTypes = new HashSet<ServiceType>();
            this.SyncDigests = new HashSet<SyncDigest>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string ExternalReference { get; set; }
        public string External_Id { get; set; }
        public Nullable<System.Guid> UM_SageCustomer_Id { get; set; }
        public string UM_SageCustomerName { get; set; }
        public string UM_SageCustomerNumber { get; set; }
        public string UM_TenantBaseUrl { get; set; }
        public string UM_TenantCode { get; set; }
        public string UM_TenantName { get; set; }
        public string AvataxAccount { get; set; }
        public string AvataxLicenseKey { get; set; }
        public string AvataxURL { get; set; }
        public string ERPCompanyCode { get; set; }
        public string ERPCompanyName { get; set; }
        public string ERPCompanyAddressLine1 { get; set; }
        public string ERPCompanyAddressLine2 { get; set; }
        public string ERPCompanyAddressLine3 { get; set; }
        public string ERPCompanyAddressLine4 { get; set; }
        public string ERPCompanyCity { get; set; }
        public string ERPCompanyRegion { get; set; }
        public string ERPCompanyCountry { get; set; }
        public string ERPCompanyPostalCode { get; set; }
        public string SyncHashKey { get; set; }
        public short SyncEndpoint_Id { get; set; }
        public int SyncEndpointTick { get; set; }
        public short EntityStatus { get; set; }
    
        public virtual ICollection<Blob> Blobs { get; set; }
        public virtual ICollection<CustomerPortalSetting> CustomerPortalSettings { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<IntegrationError> IntegrationErrors { get; set; }
        public virtual ICollection<InventoryCategory> InventoryCategories { get; set; }
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
        public virtual ICollection<ServiceType> ServiceTypes { get; set; }
        public virtual ICollection<SyncDigest> SyncDigests { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
