//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string UM_PrimaryEmail { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> UM_ProductUser_Id { get; set; }
        public Nullable<System.Guid> UM_SageIdentity_Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string PhoneMobile { get; set; }
        public string EmailWork { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
