//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAttachment
    {
        public System.Guid Id { get; set; }
        public System.Guid Tenant_Id { get; set; }
        public System.Guid WorkOrder_Id { get; set; }
        public Nullable<short> AttachmentType { get; set; }
        public string MimeTypeOriginal { get; set; }
        public string URLOriginal { get; set; }
        public Nullable<System.Guid> AzureContainerKeyOriginal { get; set; }
        public Nullable<bool> IsPrimaryOriginal { get; set; }
        public string MimeTypeThumbnail { get; set; }
        public string URLThumbnail { get; set; }
        public Nullable<System.Guid> AzureContainerKeyThumbnail { get; set; }
        public Nullable<bool> IsPrimaryThumbnail { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
